### ISSUE TITLE
Replace os.environ['KEY'] with os.environ.get(KEY')

### ISSUE THREAD

**Issue by ueg1990** [python/the-knights-who-say-ni#11]
To avoid/handle KeyError exceptions, maybe use os.environ.get and define a default value?

**Comment by brettcannon** [comment]
The problem is that if it doesn't the port doesn't exist then the whole app won't work, so making it optional through `os.environ.get()` doesn't save you anything unless you want to raise a different exception to notice that the environment variable wasn't set in Heroku.

**Comment by brettcannon** [comment]
Oh, and if Heroku doesn't set the port then there are much bigger issues to worry about. :wink:

**Comment by ueg1990** [comment]
makes sense

**Comment by brettcannon** [comment]
Thanks for at least thinking about it!
