### ISSUE TITLE
Let maintainers override "CLA Signed" labels

### ISSUE THREAD

**Issue by ambv** [python/the-knights-who-say-ni#113]
If there's already a label that says "CLA signed", the bot shouldn't remove it. This is for cases like CCLAs. See history on https://github.com/python/cpython/pull/1734 for an example.

**Comment by brettcannon** [comment]
The specific case was Łukasz wanted to override the CLA label, and so he added "CLA signed" and then removed "CLA not signed". The order of webhook events can't be known ahead of time, but with enough of a delay then getting the current labels should be enough to check if an overriding label was also added simultaneously.

**Comment by hugovk** [comment]
Closing because the Knights have been replaced by [the CLA bot](https://github.com/apps/cpython-cla-bot#-who-says-ekke-ekke-ekke-ekke-ptang-zoom-boing). See [the discussion](https://discuss.python.org/t/14961) for more details.

https://github.com/python/the-knights-who-say-ni/pull/326
