### ISSUE TITLE
Running tests locally are always failing (for me)

### ISSUE THREAD

**Issue by Mariatta** [python/the-knights-who-say-ni#125]
When running the tests locally, I see this error:

```
aiohttp.client_exceptions.ClientConnectorError: [Errno 65] Cannot connect to host bugs.python.org:443 ssl:True [Can not connect to bugs.python.org:443 [No route to host]]
```

We're seeing a similar issue in PRs https://github.com/python/the-knights-who-say-ni/pull/122 and https://github.com/python/the-knights-who-say-ni/pull/124. Closing and re-opening the PR sometimes work to make the tests pass again.

Wondering if there is something else I need to do to make my tests pass locally and not rely on luck 🍀  :crossed_fingers:

**Comment by zware** [comment]
This may be related to connection failures that @haypo has been experiencing on browsing to bugs.python.org, and which I have also seen sometimes (but for me, Chrome reloads so quickly that I just see a flash of error page before it goes on).

**Comment by brettcannon** [comment]
You can not use SSL. 😉 Otherwise there's nothing we can do.
