### ISSUE TITLE
Whitelist miss-islington

### ISSUE THREAD

**Issue by berkerpeksag** [python/the-knights-who-say-ni#127]
Can we whitelist @miss-islington so the CLA checker bot doesn't set "CLA not signed" label in backport PRs? (See https://github.com/python/cpython/pull/4005 for example.) I can create a PR to implement this.

**Comment by Mariatta** [comment]
Strange, this was supposed to be fixed already in https://github.com/python/the-knights-who-say-ni/pull/122, and https://github.com/python/cpython/pull/3973 shows that it worked.

**Comment by berkerpeksag** [comment]
That's my fault :) Original author of https://github.com/python/cpython/pull/3993 hasn't signed the CLA yet: https://bugs.python.org/user27130 Sorry for the noise.

**Comment by Mariatta** [comment]
No prob :)
Maybe as an enhancement, it can say which users have not signed the CLA. 
I think it is common in CPython that the PR contains multiple authors, not sure about other projects though.
