### ISSUE TITLE
500 error 

### ISSUE THREAD

**Issue by Mariatta** [python/the-knights-who-say-ni#135]
No CLA check on this PR: https://github.com/python/cpython/pull/5696
I tried removing the label and adding it back. 
Looking at the webhook deliveries, there's a 500 error when it was unlabeled.

Reporting this issue so we're aware of it.

**Comment by Mariatta** [comment]
Strange. The error is because the commit "author" dict is empty, see https://api.github.com/repos/python/cpython/pulls/5696/commits : 
```
"author": {

    },
```

It breaks line https://github.com/python/the-knights-who-say-ni/blob/master/ni/github.py#L141.

Not sure how it happens that a commit does not have an author..

**Comment by brettcannon** [comment]
I wonder if they played around with the git at a more fundamental level?

**Comment by Mariatta** [comment]
Not sure. I wonder if this is GitHub's bug.

Looking at the returned commits in https://api.github.com/repos/python/cpython/pulls/5696/commits:
At the top there are committer and author names, but without email address.
```
"commit": {
      "author": {
        "name": "xpvpc",
        "email": "",
        "date": "2018-02-16T09:46:49Z"
      },
      "committer": {
        "name": "xpvpc",
        "email": "",
        "date": "2018-02-16T09:46:49Z"
      },
```

Down below, the author and committer dicts are empty:
```
"author": {

    },
    "committer": {

    },
```

Interestingly, in the backport PR, we are getting their email address and author info correctly: https://api.github.com/repos/python/cpython/pulls/5698/commits

**Comment by brettcannon** [comment]
I would chalk this up to a GitHub glitch then.
