### ISSUE TITLE
Random "SSL connect failures" from the GitHub cpython webhooks

### ISSUE THREAD

**Issue by ned-deily** [python/the-knights-who-say-ni#138]
Earlier today, I noticed problems with issues on bugs.python.org not getting updated properly with GitHub events.  After investigating the webhooks on the GitHub cpython admin interface, I found that a significant number of webhook requests from GitHub to https://bugs.python.org were failing with "SSL connect failures".  There have been previous unresolved reports of more general SSL/TLS problems with b.p.o; I added the results of my findings today to an open issue on the b.p.o metatracker, http://psf.upfronthosting.co.za/roundup/meta/issue649.  I also checked the results of the other webhooks for the cpython repo and found that the connections to `the-knights-who-say-ni` server were also failing intermittently in a similar manner.  Curiously, there were no failures reported for any of the other webhooks, including the one to `miss-islington` which is also hosted at herokuapp.com and which is called with a similar frequency.  About six hours ago, I went in and had GitHub manually retry all of the failed requests (they were over an approximately 12 hour period) and this time they worked.  I've been keeping an eye on the GitHub admin logs and have not seen a repeat since then but activity has also been light.  Note that the symantec certificate checker (https://cryptoreport.websecurity.symantec.com/checker/) indicates that the server is vulnerable to a BEAST attack.  Perhaps the SSL/TLS libs in use need to be updated?   Otherwise, I'm not sure what action is needed if there are no further failures.

**Comment by gpshead** [comment]
FWIW I had SSL hash failure errors _from my browser_ on some of today's bugs.python.org connections.

**Comment by Mariatta** [comment]
I've seen the same SSL errors when running the-knights' test suite locally, and I think it also happened several times with travis CI. (see related issue: https://github.com/python/the-knights-who-say-ni/issues/125)

>  Curiously, there were no failures reported for any of the other webhooks, including the one to miss-islington which is also hosted at herokuapp.com and which is called with a similar frequency. 

The SSL errors come from making API calls to b.p.o, when we check if user has signed the CLA. miss-islington does not make such calls, so it's expected that there were little or no failures coming from miss-islington :)

Although I'm not sure if there's anything we can do from within the-knights-who-say-ni, but maybe in `aiohttp`?

**Comment by asvetlov** [comment]
aiohttp uses system certificates provided by `ssl` module.
`ssl.create_default_context()` actually.

**Comment by Mariatta** [comment]
Seeing some more SSL certificate errors, logged in https://github.com/python/core-workflow/issues/259#issuecomment-396044348

**Comment by Mariatta** [comment]
Failure still occurs, logged in python/core-workflow#259
See also python/psf-infra-meta#4

**Comment by arhadthedev** [comment]
> I found that a significant number of webhook requests from GitHub to https://bugs.python.org/ were failing with "SSL connect failures"

Is the issue relevant after the migration?

**Comment by JelleZijlstra** [comment]
The whole repo is no longer relevant. I think there are plans to archive it?

**Comment by hugovk** [comment]
There are plans: https://github.com/python/the-knights-who-say-ni/pull/326

Closing because the Knights have been replaced by [the CLA bot](https://github.com/apps/cpython-cla-bot#-who-says-ekke-ekke-ekke-ekke-ptang-zoom-boing). See [the discussion](https://discuss.python.org/t/14961) for more details.
