### ISSUE TITLE
GitHub sending us PR synchronize event for a PR that does not exist.

### ISSUE THREAD

**Issue by Mariatta** [python/the-knights-who-say-ni#148]
We keep receiving a pull_request synchronize event for PR 5581 (https://github.com/python/cpython/pull/5581) which doesn't actually exist.

It's causing the error `gidgethub.BadRequest: Not Found` in here:
https://github.com/python/the-knights-who-say-ni/blob/be76a78fea5b57042d509645e0e3fd96a041e9d5/ni/github.py#L139-L141

I've filed an issue with GitHub to stop sending us such event, but maybe we can catch the exception here.

**Comment by brettcannon** [comment]
Great, non-existent stuff. Yeah, we can catch it and just quit out since if GitHub is giving us bad data there's nothing we can do but log that fact.

**Comment by Mariatta** [comment]
Update from GitHub:

PR 5581 exists, but it just has been marked as "suspicious/spammy", so we and the bots can't access it. The PR was still open and we were receiving the "`synchronize`" events, breaking the bots.

I have asked GitHub to close the PR, and it has been closed now.

We can still improve the code though if this ever happens again :)

**Comment by hugovk** [comment]
Closing because the Knights have been replaced by [the CLA bot](https://github.com/apps/cpython-cla-bot#-who-says-ekke-ekke-ekke-ekke-ptang-zoom-boing). See [the discussion](https://discuss.python.org/t/14961) for more details.

https://github.com/python/the-knights-who-say-ni/pull/326
