### ISSUE TITLE
Provide the link to check CLA status in the comment. 

### ISSUE THREAD

**Issue by Mariatta** [python/the-knights-who-say-ni#159]
The "check yourself" link currently links to devguide section that explains which API endpoint to use, and how to interpret the response.

https://github.com/python/the-knights-who-say-ni/blob/08b8eb078b44a7f213c50f4fe49907f401eec954/ni/github.py#L41

Perhaps we can also provide the actual link to the API endpoint, complete with the usernames to check .

**Comment by brettcannon** [comment]
If you want to get really fancy we can create a page with some simple JavaScript that asks the person to fill in their GitHub username, makes an XHR call, and then displays the results. 😁

**Comment by Mariatta** [comment]
Fancy challenge accepted.  😃 

<img width="454" alt="screen shot 2018-08-09 at 2 29 26 pm" src="https://user-images.githubusercontent.com/5844587/43926952-c144b2cc-9be0-11e8-8a56-40a2322857eb.png">

**Comment by Mariatta** [comment]
So I got really fancy: https://check-python-cla.herokuapp.com/
Code: https://github.com/mariatta/check_python_cla

**Comment by Mariatta** [comment]
Thanks 😄 Currently it is on Heroku's free tier.
@ewdurbin Can this be hosted by The PSF instead of on my personal heroku account?

**Comment by ewdurbin** [comment]
@Mariatta absolutely, do you want to transfer the app or should we just create a new one and grant you access.

**Comment by Mariatta** [comment]
I can just transfer it, but maybe I need other permission in order to do the transfer?

<img width="924" alt="screen shot 2018-08-10 at 12 56 14 pm" src="https://user-images.githubusercontent.com/5844587/43978695-fcd2f288-9c9c-11e8-9b63-585ffa22e10a.png">

**Comment by ewdurbin** [comment]
@Mariatta I invited your user on Heroku to be a member of the team rather than a collaborator. You should be able to initiate a transfer now.
