### ISSUE TITLE
Return a 200 on a successful ping event

### ISSUE THREAD

**Issue by brettcannon** [python/the-knights-who-say-ni#27]

**Comment by ueg1990** [comment]
how would one do a ping event?

**Comment by brettcannon** [comment]
Do you mean personally, or what triggers it?

Whenever GitHub registers a new hook it sends a ping event to verify the webhook is functioning properly to accept notifications. If you're asking how it's tested for, a [test exists](https://github.com/python/the-knights-who-say-ni/blob/89306b9163b770998561cbcd49ab0d1114858ccd/ni/test/test_github.py#L71) for this.

**Comment by ueg1990** [comment]
Can i take this issue? I kindof have an idea what to do but I am just confused what is the best way to do it. This is what i am thinking; in github.py:
1) Define a new useful action in _useful_actions; maybe 'ping' or 'zen'
2) Add a new condition in method update, just return something like 'await "ping"' or 'await None' (I am not sure what is the best option)
3) And then in function handler, when we return to 'await contribution.update(cla_status)', the response will return as 200

Let me know what you think

**Comment by brettcannon** [comment]
Yes, please take the issue!

As for your proposed approach, I think it's more engineering than necessary since the ping event currently doesn't do anything but immediately return. Simply update the [ping detection to return a 200](https://github.com/python/the-knights-who-say-ni/blob/bd1ad6bd14764e0f5252a9d7d2bc5a1e1a967042/ni/github.py#L89), and then [update the test](https://github.com/python/the-knights-who-say-ni/blob/bd1ad6bd14764e0f5252a9d7d2bc5a1e1a967042/ni/test/test_github.py#L78) appropriately.
