### ISSUE TITLE
PRs that need a CLA don't get resubmitted for checks

### ISSUE THREAD

**Issue by PenelopeFudd** [python/the-knights-who-say-ni#316]
I created a PR (https://github.com/python/cpython/pull/31319), but had not signed a CLA at that time.

I completed the CLA process, and the-knights-who-say-ni updated the PR status:
![image](https://user-images.githubusercontent.com/1606480/160209217-ae76529f-1eb0-4f31-8aa3-bc09ca19b881.png)

At that point, one might have expected the PR checks to run, but they haven't yet and it's been 40 days.

![image](https://user-images.githubusercontent.com/1606480/160209109-f0f2a17f-7111-4890-9715-d1e3d54383a5.png)

As a workaround, I suppose I could resubmit my PR, but it looks like the process was designed to restart the checks when the CLA is signed.

Hopefully this will lower the barrier for other new contributors, making Python better for everyone!

**Comment by AlexWaygood** [comment]
This isn't anything to do with the-knights-who-say-ni, I'm afraid — this is a github feature that means that maintainers of an open-source project have to manually approve the CI workflow for first-time contributors. I believe that this is to prevent spammers (which you evidently are not) triggering the CI on PRs all the time.

**Comment by JelleZijlstra** [comment]
Yes, the CLA bot seems to be fine. I closed and reopened the PR to trigger the rest of CI.

**Comment by PenelopeFudd** [comment]
Ok, thanks!

I'd figured that signing the CLA was also being used anti-spammer device, which would trigger the rest of CI, but I imagine that even with that, there's a sufficient volume of spammers getting through.  :-/

Ni!  😃
