### ISSUE TITLE
Use aiohttp's fake request object

### ISSUE THREAD

**Issue by brettcannon** [python/the-knights-who-say-ni#43]
http://aiohttp.readthedocs.io/en/latest/testing.html#faking-request-object

**Comment by berkerpeksag** [comment]
https://bugs.python.org/issue26467 is a blocker to use aiohttp's `make_mocked_request()` helper.

**Comment by hugovk** [comment]
Closing because the Knights have been replaced by [the CLA bot](https://github.com/apps/cpython-cla-bot#-who-says-ekke-ekke-ekke-ekke-ptang-zoom-boing). See [the discussion](https://discuss.python.org/t/14961) for more details.

https://github.com/python/the-knights-who-say-ni/pull/326
