### ISSUE TITLE
TKWSN not recognizing @gvanrossum

### ISSUE THREAD

**Issue by zware** [python/the-knights-who-say-ni#52]
In python/peps#70, @the-knights-who-say-ni doesn't seem to recognize our BDFL, though http://bugs.python.org/user?github=gvanrossum&@action=search comes up with his account just fine.

**Comment by brettcannon** [comment]
The failure on that PR to be cleared for CLA signing is because @gvanrossum has commits in his PR from @kirbyfan64 who has not signed the CLA; it has nothing to do with Guido.

**Comment by zware** [comment]
I just realized that's what was going on.  Sorry for the noise.

**Comment by brettcannon** [comment]
I just opened #53 for using a less boilerplate message from the bot by specifying who is causing the issue(s).
