### ISSUE TITLE
Make the message provide a TODO list for people

### ISSUE THREAD

**Issue by brettcannon** [python/the-knights-who-say-ni#69]
E.g. a bullet point list so people know what they exactly what they have to do. If it's feasible, even make them checkoff lists if it turns out anyone can check them off.

**Comment by the-knights-who-say-ni** [comment]
Testing what it's like when someone else makes a checkbox:

- [ ] Hello
- [ ] How are you?

**Comment by brettcannon** [comment]
Looks like non-project owners can't check off the boxes in the comment, so the TODO list will need to just be a bullet list.
