### ISSUE TITLE
Add type hints to the test suite

### ISSUE THREAD

**Issue by brettcannon** [python/the-knights-who-say-ni#81]
Adding type hints throughout the test suite would help make sure that the various fake objects actually met the type restrictions of what they were faking. The real trick is cleaning up test code that's taking shortcuts where changing the type hints to match the test suite would weaken the type checks (e.g. making things `Optional` just because `None` was used in the test suite to be lazy).

- [ ] ni.test.util
- [ ] ni.test.test_bpo
- [ ] ni.test.test_github
- [ ] ni.test.test_heroku
- [ ] ni.test.test_main

**Comment by hugovk** [comment]
Closing because the Knights have been replaced by [the CLA bot](https://github.com/apps/cpython-cla-bot#-who-says-ekke-ekke-ekke-ekke-ptang-zoom-boing). See [the discussion](https://discuss.python.org/t/14961) for more details.

https://github.com/python/the-knights-who-say-ni/pull/326
