### ISSUE TITLE
Sometimes bot does not add "CLA signed" label

### ISSUE THREAD

**Issue by ilevkivskyi** [python/the-knights-who-say-ni#87]
I have noticed that last three-four days the bot did not always add the "CLA signed" label to PRs by someone who has signed the CLA. For example, this happened to me: https://github.com/python/typing/pull/375

Unfortunately, I do not know how to reproduce this (could be related to #86)

**Comment by brettcannon** [comment]
I'm fairly certain it is #86 as this started to happen suddenly with no code changes to affect it.

And re-running the CLA bot on a PR is easy as adding a label like "CLA not signed" and then removing it so there's no direct harm other than someone needing to do that step.
