### ISSUE TITLE
CLA not signed ?

### ISSUE THREAD

**Issue by Mariatta** [python/the-knights-who-say-ni#98]
🤔 Did I do something wrong here? 😅 
The bot seemed to think that I haven't signed the CLA. But I definitely did..

https://github.com/python/cpython/pull/468 and https://github.com/python/cpython/pull/467

**Comment by brettcannon** [comment]
You did, but jw4js probably hasn't and that's who authored the PR (e.g. see https://github.com/python/cpython/pull/468/commits). GH-53 is an open issue to make this more clear in the message itself for these rare cases where a PR has multiple authors.
